### ISSUE TITLE
Multi user selection does not work

### ISSUE THREAD

**Issue by lucke76** [supernova13892/whatsapp_stalker#9]
Hi, today the multiuser selection for contact stopped working, when i select a contact it works for some seconds but eventually stuck everytime with a contact whitout completing the cycle.

The error it gives is Uncaught TypeError: Cannot read property 'dispatchEvent' of undefined at contact_span.parents("._3NWy8")[0].dispatchEvent(mouse_evt);

Could you fix this? Your extension is great.

**Comment by Jerrykooij** [comment]
@supernova13892 please try to fix, i have been trying myself and it seems to be a easy fix but i cant find out...

**Comment by stzippy** [comment]
Hi, same issue for me since today. If helpful, here the errors shown on screen:

DevTools listening on ws://127.0.0.1:50578/devtools/browser/7f991cd6-5bb4-46b2-b831-33a925d42451
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "whatsapp-monitor.py", line 83, in start
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 564, in find_element_by_class_name
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"._19vo_"}
  (Session info: chrome=80.0.3987.149)

Thanks for your help fixing this. :)

**Comment by tyren542** [comment]
No one figured how to make it work? I think the problem is that watsapp changed the class

**Comment by rizwansoaib** [comment]
> No one figured how to make it work? I think the problem is that watsapp changed the class

https://github.com/rizwansoaib/whatsapp-monitor

**Comment by supernova13892** [comment]
I have updated the classes, and will make this project stable again.

**Comment by Jerrykooij** [comment]
multiuser selection seems to be working again, nice!

but i noticed that right now it doesnt track the online times anymore?
there are no recordings when i tried tracking myself and something weird
seems to be going on in the search chat bar when starting stalking.
apart from that you have made a very nice tool here, i have been using it
for a while. whenever i have some spare money i will donate you something.
much appreciated!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
